[2025-04-23T20:13:53.376+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:13:53.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:13:53.380+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:13:53.379+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:13:53.407+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:13:53.401+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:13:53.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:13:53.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.072 seconds
[2025-04-23T20:14:24.119+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:14:24.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:14:24.124+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:24.124+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:14:24.150+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:24.143+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:14:24.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:14:24.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.060 seconds
[2025-04-23T20:14:54.915+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:14:54.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:14:54.920+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:54.919+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:14:54.940+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:14:54.936+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:14:54.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:14:54.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.053 seconds
[2025-04-23T20:15:26.022+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:15:26.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:15:26.054+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:26.051+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:15:26.163+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:26.142+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:15:26.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:15:26.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.216 seconds
[2025-04-23T20:15:56.886+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:15:56.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:15:56.892+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:56.891+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:15:56.917+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:15:56.912+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:15:56.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:15:56.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.066 seconds
[2025-04-23T20:16:27.687+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:16:27.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:16:27.692+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:27.691+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:16:27.717+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:27.712+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:16:27.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:16:27.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.066 seconds
[2025-04-23T20:16:58.501+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:16:58.503+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:16:58.506+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:58.506+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:16:58.534+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:16:58.529+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:16:58.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:16:58.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.068 seconds
[2025-04-23T20:17:29.437+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:17:29.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:17:29.442+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:17:29.441+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:17:29.469+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:17:29.464+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:17:29.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:17:29.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.065 seconds
[2025-04-23T20:20:31.681+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:20:31.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:20:31.686+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:20:31.686+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:20:31.716+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:20:31.710+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:20:31.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:20:31.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.071 seconds
[2025-04-23T20:21:02.437+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:21:02.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:21:02.443+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:02.442+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:21:02.467+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:02.461+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:21:02.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:21:02.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.066 seconds
[2025-04-23T20:21:33.115+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:21:33.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:21:33.120+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:33.119+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:21:33.145+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:21:33.140+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:21:33.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:21:33.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.060 seconds
[2025-04-23T20:22:03.823+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:22:03.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:22:03.829+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:03.828+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:22:03.860+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:03.855+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:22:03.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:22:03.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.072 seconds
[2025-04-23T20:22:34.562+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:22:34.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:22:34.567+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:34.566+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:22:34.591+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:22:34.585+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:22:34.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:22:34.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.061 seconds
[2025-04-23T20:23:06.263+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:23:06.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:23:06.269+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:06.268+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:23:06.290+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:06.286+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:23:06.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:23:06.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.056 seconds
[2025-04-23T20:23:38.989+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:23:38.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:23:38.993+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:38.993+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:23:39.013+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:23:39.010+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:23:39.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:23:39.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.056 seconds
[2025-04-23T20:24:10.644+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:24:10.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:24:10.649+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:10.649+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:24:10.672+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:10.668+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:24:10.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:24:10.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.061 seconds
[2025-04-23T20:24:43.371+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:24:43.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:24:43.379+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:43.378+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:24:43.409+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:24:43.402+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:24:43.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:24:43.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.091 seconds
[2025-04-23T20:25:13.739+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:25:13.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:25:13.745+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:13.745+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:25:15.139+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:15.133+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:25:15.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:25:15.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.075 seconds
[2025-04-23T20:25:47.898+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:25:47.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:25:47.901+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:47.901+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:25:47.923+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:25:47.918+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:25:47.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:25:47.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.052 seconds
[2025-04-23T20:26:18.169+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:26:18.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:26:18.175+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:18.174+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:26:19.584+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:19.575+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:26:19.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:26:19.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.083 seconds
[2025-04-23T20:26:52.255+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:26:52.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:26:52.260+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:52.260+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:26:52.282+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:26:52.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:26:52.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:26:52.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.057 seconds
[2025-04-23T20:27:24.131+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:27:24.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:27:24.150+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:24.150+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:27:24.244+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:24.229+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:27:24.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:27:24.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.280 seconds
[2025-04-23T20:27:56.267+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:27:56.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:27:56.275+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:56.273+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:27:56.316+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:27:56.310+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:27:56.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:27:56.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.106 seconds
[2025-04-23T20:28:27.075+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:28:27.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:28:27.084+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:28:27.083+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:28:28.484+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:28:28.476+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:28:28.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:28:28.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.099 seconds
[2025-04-23T20:29:01.185+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:29:01.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:29:01.189+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:01.189+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:29:01.209+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:01.205+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:29:01.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:29:01.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.051 seconds
[2025-04-23T20:29:32.991+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:29:32.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:29:33.000+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:32.999+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:29:33.033+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:29:33.026+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:29:33.036+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:29:33.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.104 seconds
[2025-04-23T20:30:05.679+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:30:05.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:30:05.687+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:05.686+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:30:05.728+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:05.721+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:30:05.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:30:05.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.091 seconds
[2025-04-23T20:30:37.402+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:30:37.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:30:37.405+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:37.405+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:30:37.427+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:30:37.422+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:30:37.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:30:37.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.052 seconds
[2025-04-23T20:31:10.029+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:31:10.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:31:10.033+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:10.032+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:31:10.053+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:10.049+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:31:10.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:31:10.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.052 seconds
[2025-04-23T20:31:42.152+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:31:42.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:31:42.156+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:42.156+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:31:42.180+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:31:42.175+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:31:42.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:31:42.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.060 seconds
[2025-04-23T20:32:14.914+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:32:14.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:32:14.922+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:14.921+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:32:14.957+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:14.947+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:32:14.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:32:15.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.100 seconds
[2025-04-23T20:32:46.751+0000] {processor.py:186} INFO - Started process (PID=520) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:32:46.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:32:46.756+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:46.755+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:32:46.780+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:32:46.774+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:32:46.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:32:46.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.064 seconds
[2025-04-23T20:33:18.605+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:33:18.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:33:18.610+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:18.610+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:33:18.630+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:18.625+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:33:18.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:33:18.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.056 seconds
[2025-04-23T20:33:49.383+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:33:49.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:33:49.389+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:49.388+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:33:50.779+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:33:50.774+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:33:50.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:33:50.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.059 seconds
[2025-04-23T20:34:23.434+0000] {processor.py:186} INFO - Started process (PID=565) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:34:23.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:34:23.441+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:23.440+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:34:23.469+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:23.463+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:34:23.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:34:23.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.079 seconds
[2025-04-23T20:34:53.770+0000] {processor.py:186} INFO - Started process (PID=580) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:34:53.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:34:53.774+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:53.773+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:34:53.794+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:34:53.790+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:34:53.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:34:53.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.054 seconds
[2025-04-23T20:35:24.573+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:35:24.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:35:24.577+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:24.576+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:35:24.595+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:24.591+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:35:24.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:35:24.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.049 seconds
[2025-04-23T20:35:55.301+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/lab1.py
[2025-04-23T20:35:55.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab1.py for tasks to queue
[2025-04-23T20:35:55.305+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:55.305+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/lab1.py
[2025-04-23T20:35:55.326+0000] {logging_mixin.py:190} INFO - [2025-04-23T20:35:55.321+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/lab1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab1.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-04-23T20:35:55.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab1.py
[2025-04-23T20:35:55.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab1.py took 0.054 seconds
